name: Kristin Chalmers Creative
favicon: null
layout_spectrum: 0.27224
typography_spectrum: 0.82873
title: 'music, food and lifestyle photography '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9b9b9'
    - '#424242'
    - '#dcdcdc'
    - '#8a8a8a'
    - '#070707'
  brandStrength: 0.6995355058461428
  lightness: 0.424719347152859
  saturation: 0.978161655832082
  rhythmicContrast: 0.8426604263950139
purpose: []
